"""initial migration

Revision ID: 12d5b7dd3448
Revises: 
Create Date: 2024-02-16 08:42:40.116889

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '12d5b7dd3448'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_code', sa.String(length=5), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('shelf_life', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('product_code'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('racks',
    sa.Column('rack_id', sa.String(length=5), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('rack_id'),
    sa.UniqueConstraint('rack_id')
    )
    op.create_table('samples_referenced',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rack_id', sa.String(length=5), nullable=True),
    sa.Column('product_code', sa.String(length=5), nullable=True),
    sa.Column('batch_number', sa.String(length=5), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('destroy_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.rack_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('samples_retained',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rack_id', sa.String(length=5), nullable=True),
    sa.Column('product_code', sa.String(length=5), nullable=True),
    sa.Column('batch_number', sa.String(length=5), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('destroy_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_code'], ['products.product_code'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.rack_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samples_retained')
    op.drop_table('samples_referenced')
    op.drop_table('racks')
    op.drop_table('products')
    # ### end Alembic commands ###
