"""Add timestamp field on audit table

Revision ID: 20d3924b4747
Revises: 6fbd33ee3e59
Create Date: 2024-02-29 08:52:45.924104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d3924b4747'
down_revision: Union[str, None] = '6fbd33ee3e59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'timestamp')
    # ### end Alembic commands ###
