"""Change response to request on audit

Revision ID: 6fbd33ee3e59
Revises: 6447510f8744
Create Date: 2024-02-28 21:58:53.966663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fbd33ee3e59'
down_revision: Union[str, None] = '6447510f8744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('request', sa.String(length=255), nullable=True))
    op.drop_column('audit', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('response', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('audit', 'request')
    # ### end Alembic commands ###
