"""Update Rack model (add retained_sample and referenced_sample relationships)

Revision ID: b54d64d53d9f
Revises: 173772f49d99
Create Date: 2024-02-26 09:00:54.657652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54d64d53d9f'
down_revision: Union[str, None] = '173772f49d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racks', sa.Column('max_stored', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('racks', 'max_stored')
    # ### end Alembic commands ###
