"""Add product_type and package on product table

Revision ID: ee215863e966
Revises: 5573f3e75bd4
Create Date: 2024-03-08 13:02:51.252887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee215863e966'
down_revision: Union[str, None] = '5573f3e75bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(length=10), nullable=True))
    op.add_column('products', sa.Column('package', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'package')
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
